data:
  data_dir: ./data
  symbols: [BTCUSDT]
  months: ["2025-01"]
  resample_interval: 1min
broker:
  initial_capital: 100000
  taker_fee_bps: 1.0
  slippage_bps: 0.5
  latency_ms: 50
strategy:
  momentum_windows: [60, 240, 720, 1440]
  breakout_lookback: 300
  vol_window: 1440
  target_vol_annual: 0.3
  max_leverage: 3.0
run:
  log_level: INFO
  write_trades: true
  write_equity: true
