data:
  data_dir: ./data
  symbols:
  - BTCUSDT
  - ETHUSDT
  - SOLUSDT
  months:
  - 2025-01
  - 2025-02
  - 2025-03
  - 2025-04
  - 2025-05
  - 2025-06
  - 2025-07
  resample_interval: 1min
broker:
  initial_capital: 100000.0
  taker_fee_bps: 7.5
  slippage_bps: 1.5
  latency_ms: 500
strategy:
  momentum_windows:
  - 60
  - 240
  - 720
  - 1440
  breakout_lookback: 300
  vol_window: 1440
  target_vol_annual: 0.3
  max_leverage: 3.0
run:
  log_level: INFO
  write_trades: true
  write_equity: true
