seed: 42

paths:
  inputs_dir: "inputs"
  outputs_dir: "outputs"

symbols: ["BTCUSDT", "ETHUSDT", "SOLUSDT"]

data:
  # Months you actually have (edit freely)
  months: ["2025-01","2025-02","2025-03","2025-04","2025-05","2025-06","2025-07","2025-08"]

features:
  atr_window: 50
  donchian_lookback: 55

regime:
  macro_window: 240
  macro_tmin: 2.0
  cooldown_bars_after_flip: 15

micro:
  short_window: 30
  long_window: 90
  tmin: 1.7          # ↑ slightly stricter
  accel_min: 0.7     # ↑ require more acceleration

entry:
  atr_buffer_mult: 0.12      # ↓ was 0.20 (easier to trigger but still buffered)
  min_body_atr_mult: 0.25    # NEW: candle body ≥ 0.25×ATR at breakout
  flat_cooldown_bars: 10     # NEW: wait after any exit

filters:
  atr_pctile_window: 720     # ~12h percentile window on 1m bars
  atr_pctile_min: 40         # trade only when ATR% is above 40th pct

risk:
  sl_atr_mult: 15.0
  tp_atr_mult: 30.0          # ↓ was 60.0: easier TP → higher hit rate
  breakeven_r: 0.35          # arm BE a bit earlier
  sl_exact_neg1: true
  barrier_priority: "worst"   # "worst" (default) | "best" | "tp_first" | "sl_first"

walkforward:
  train_months: 3
  test_months: 1
  step_months: 1
