paths:
  inputs_dir: "inputs"
  outputs_dir: "outputs"

symbols: ["BTCUSDT", "ETHUSDT", "SOLUSDT"]

months: ["2025-01","2025-02","2025-03","2025-04","2025-05","2025-06","2025-07"]

warmup:
  min_1m_bars: 1000  # ensure indicators populated

regime:
  ts_mom:
    require_majority: 4          # 4 of 5
    timeframes:
      - tf: "1min"   # 1-minute
        lookback_closes: 3
      - tf: "5min"
        lookback_closes: 3
      - tf: "15min"
        lookback_closes: 3
      - tf: "1h"
        lookback_closes: 3
      - tf: "5h"     # NEW timeframe
        lookback_closes: 3

waves:
  enabled: true
  timeframe: "event"             # "event" uses CUSUM bars
  cusum:
    k_factor: 0.45               # κ = k_factor * ATR_1m(200)
    k_min: 0.35
    k_max: 0.70
    atr_window_1m: 200
  zigzag:
    atr_window: 220
    atr_mults: [1.8, 3.0, 5.0]
    max_lookback_bars: 2000      # count of event bars (enough; 2k events)
  thresholds:
    min_confidence: 0.60
    w2_posterior_min: 0.60
    w2_end_arm: 0.62
    max_age_impulse_bars: 110    # in event bars; additionally enforce ≥5h 1m coverage

entry:
  mode: "baseline"
  momentum:
    zscore_window: 20
    zscore_k: 2.0
    min_body_dom: 0.6
    range_atr_min: 1.5
    buffer_atr_mult: 0.30

risk:
  atr:
    window: 14
  sl:
    mode: "structure_or_atr"
    atr_mult: 5.0
  be:
    trigger_r: 0.75
    buffer:
      r_multiple: 0.02           # small > 0R to cover friction
      fees_bps_round_trip: 7
      slippage_bps: 5
  tsl:
    start_r: 1.4
    atr_mult: 3.6

position:
  qty_mode: "notional"  # "units" or "notional"
  notional_usd: 100      # used for P&L scaling; no brokerage here

logging:
  progress: true
  debug_blockers: true
  progress_stride: 50     # update hook every N bars
  overall_bar: true       # show combined progress bar across symbols
