# configs/default.yaml
# WaveGate + Momentum Backtest (looser sweep baseline) — all thresholds in YAML

paths:
  inputs_dir: "inputs"
  outputs_dir: "outputs"

symbols: ["BTCUSDT"]   # run one at a time while tuning; add ["ETHUSDT","SOLUSDT"] later

# Months to backtest (UTC). Keep long enough to satisfy warmups and event coverage.
months: ["2025-01", "2025-02", "2025-03", "2025-04", "2025-05", "2025-06", "2025-07"]

logging:
  progress: true
  progress_stride: 200    # bars per UI refresh

engine:
  warmup:
    min_1m_bars: 1200     # ~20h warmup to populate zscore/ATR/regime safely
    min_w2_candidates: 25 # ensure WaveGate has enough W2 samples to set quantile thresholds

# -------- Regime (TSMOM) --------
regime:
  ts_mom:
    require_majority: 2    # need 2 TFs agreeing to avoid FLAT
    timeframes:
      - { tf: "1min",  lookback_closes: 30 }  # ~30 minutes
      - { tf: "5min",  lookback_closes: 24 }  # ~2 hours
      - { tf: "15min", lookback_closes: 16 }  # ~4 hours

# -------- Waves (CUSUM event-time bars + ZigZag/Arm) --------
waves:
  cusum:
    atr_window_1m: 200     # κ baseline from 1m ATR
    k_factor: 0.35         # κ = ATR * k_factor, clamped to [k_min, k_max]
    k_min: 0.25
    k_max: 0.60

  zigzag:
    max_lookback_bars: 1200  # event bars considered in WaveGate

  adaptive:
    enabled: true
    vol_window_1m: 600        # percentile window for vol state

    # Event-ATR smoothing & swing sensitivity (loosen for more W2 arms)
    atr_window_range: [90, 260]       # shorter smoothing → more responsive
    atr_mult_range:   [1.00, 1.80]    # smaller swing threshold → arms easier

    # Quantile to derive live thresholds from recent W2 stats
    thresholds_quantile: 0.35         # below median → very permissive

    # Hints used only before enough live W2 samples exist (explicit to avoid any hardcoded defaults)
    w2_end_arm_hint: 0.50             # permissive prewarm arm
    w2_post_min_hint: 0.50
    min_conf_hint:    0.45

    # Clamp for W2 age (event bars) — adapts from observed median; keep reasonable ceiling
    max_age_bars_range: [80, 300]     # allow older W2s if structure is clean

# -------- Entry (Momentum Power Bar) --------
entry:
  momentum:
    zscore_window: 20                 # z-score window on 1m log returns
    min_body_dom: 0.50                # body dominance threshold (|close-open|/(high-low))

  adaptive:
    enabled: true
    # Looser → more triggers; tied to vol percentile
    zscore_k_range:      [0.60, 1.00]   # very permissive momentum gate
    range_atr_min_range: [0.60, 0.90]   # allows smaller TR/ATR expansions

    # (No hardcoded fallbacks in code; these ranges fully determine trigger thresholds.)

# -------- Risk (BE / TSL / SL) --------
risk:
  accounting:
    sl_exact_neg1: true         # force r_sl = -1.0 per SL exit
    record_sl_overshoot: true   # log (realized + 1.0) as r_sl_overshoot
    min_r0_bps: 0.5             # floor r0 to avoid micro denominators (0.5 bps of entry)
  atr:
    window: 50                        # ATR for risk stop logic

  sl:
    mode: "ATR_or_Structure"          # code uses structure vs ATR combo; keep explicit
    atr_mult: 25.0                     # slightly tighter initial stop to realize risk faster

  be:
    buffer:
      r_multiple: 0.05                # BE buffer floor as fraction of r0 (prevents nicking)
      fees_bps_round_trip: 8.0        # model friction explicitly
      slippage_bps: 5.0

  adaptive:
    enabled: true
    # Make BE arm earlier and TSL start sooner so TSL actually shows up in exits.
    be_trigger_r_range: [0.30, 0.50]  # arms BE early
    tsl_start_r_range:  [0.60, 0.90]  # trail engages quickly
    tsl_atr_mult_range: [15.0, 20.0]  # tight trail to force TSL exits

# ---- Notes for sweep control (optional) ----
# You can create multiple YAMLs (e.g., default_loose.yaml, default_mid.yaml) that vary only these blocks:
# - waves.adaptive.{atr_window_range, atr_mult_range, thresholds_quantile, hints}
# - entry.adaptive.{zscore_k_range, range_atr_min_range}
# - risk.adaptive.{be_trigger_r_range, tsl_start_r_range, tsl_atr_mult_range}
#
# Example commands:
#   python -m run_backtest --config configs/default_max.yaml --workers 1

backtest:
  mode: "walkforward"     # "insample" | "oos" | "walkforward"
  oos_last_k_months: 2
  walkforward:
    train_months: 3
    test_months: 1
    step_months: 1
