seed: 42
bar_interval_minutes: 60     # 1h bars = light enough for live + multi-horizon

universe:
  - symbol: BTCUSDT
  - symbol: ETHUSDT

fees:
  taker_bps: 5
  maker_bps: 2

slippage:
  bps: 2

risk:
  equity_start: 100000.0
  target_annual_vol: 0.12
  max_gross_leverage: 3.0
  per_symbol_risk_cap_frac: 0.25
  daily_loss_stop_frac: 0.08

signals:
  # multi-horizon on 1h bars
  tsmom_lookbacks: [20, 60, 120]
  tsmom_consensus_min_abs: 2
  compression_bb_n: 72
  compression_percentile: 30
  breakout_mode: "donchian"   # or "ksigma"
  donchian_n: 55
  k_sigma_k: 2.0
  k_sigma_lookback: 72
  volume_filter: false

risk_mgmt:
  atr_n: 20
  atr_sl_mult: 20.0
  atr_tp_mult: 80.0
  breakeven_progress_frac: 0.4
  trail_atr_mult: 10.0
  use_trailing: true

streaming:
  source: live
  chunksize: 1000000              # used only for CSV warmup
  equity_recording: "bar_close"
  equity_interval_ticks: 100000
  checkpoint_stride_bars: 100

  # --- optional warm-up from CSV(s) BEFORE going live ---
  warmup_csv_files: []            # e.g.: ["data/BTCUSDT-2025-01_to_2025-07.csv", "data/ETHUSDT-2025-01_to_2025-07.csv"]

  live:
    provider: binance
    channel: aggTrade             # aggTrade or trade
    reconnect: true
    reorder_ms: 500               # holdback to order multi-symbol ticks by trade time
    ping_interval: 15
    ping_timeout: 20
    max_queue: 200000
    endpoint: wss://stream.binance.com:9443/stream   # auto-builds combined streams
    # If you *must* point to a proxy endpoint, override here.
    
fast:
  entry_on_bar_close: true

validation:
  param_grid: {}
  white_reality_check:
    enabled: false
  bootstrap:
    enabled: true
    reps: 1000
    method: stationary
    block_p: 0.1
