logging:
  level: INFO

universe:
  symbols: ["BTCUSDT", "SOLUSDT", "ETHUSDT"]

exchange:
  ccxt_id: binance
  taker_fee_bps: 7.5
  sandbox: false

# Equity used for backtest sizing (purely for simulation; match live if needed)
account:
  equity_usd: 10000.0

strategy:
  tsmom_regime:
    signal_norm:
      method: stdev
      vol_window: 20
      ewma_halflife_bars: 10
    timeframes:
      "1m":   { lookback_closes: 30 }
      "5m":   { lookback_closes: 20 }
      "15m":  { lookback_closes: 12 }
      "1h":   { lookback_closes: 8 }
    consensus:
      weights: { "1m": 0.2, "5m": 0.3, "15m": 0.3, "1h": 0.2 }
      long_threshold:  0.6
      short_threshold: -0.6
      neutral_buffer:  0.0

  trigger:
    gating:
      require_recent_compression: true
    compression:
      bb_window: 40
      min_squeeze_bars: 5
      lookback_for_recent_squeeze: 60
    breakout:
      primary: "donchian"
      donchian_lookback: 60
      buffer_atr_mult: 1.5
      ksigma:
        enabled: false
        k: 2.0
        mean_window: 50
        stdev_window: 50

entry:
  mode: "baseline"            # "baseline" | "thrust_breakout" | "retest_ignition"

  thrust:
    zscore_window: 20
    zscore_k: 1.5
    min_body_dom: 0.6         # (close-open)/(high-low), use sign for direction
    buffer_atr_mult: 0.25     # entry buffer beyond trigger level

  retest:
    retrace_min_atr: 0.3      # shallow retrace band
    retrace_max_atr: 0.6
    time_limit_bars: 30       # must re-ignite quickly
    confirm_z_k: 0.8
    min_body_dom: 0.5
    confirm_lookback: 10      # micro high/low lookback for re-break
    buffer_atr_mult: 0.25

risk:
  atr:
    window: 14
    smoothing: ema
    ema_halflife_bars: 10

  stops:
    # Defaults; symbols can override in `symbols` section
    initial_sl_atr_mult_default: 2.0
    take_profit_atr_mult: 10.0

    move_to_breakeven:
      trigger_r_multiple: 0.5  # Move to breakeven after 1.0 R profit
      be_offset_atr: 0.5   # ≥0.5 ATR recommended

    trailing:
      trail_atr_mult_default: 3.0
      step_atr: 0.75
      activate_after_be: true
      activate_after_r_multiple: 0.5 # Activate trailing after 1.0 R profit
      min_gap_atr: 5.0

  vol_targeting:
    sizing:
      per_trade_risk_cap_pct_equity: 1.0
      max_leverage: 1.0
    per_symbol_notional_cap_pct_equity: 100.0

execution:
  entry_order_type: market
  prefer_maker: false

# Exchange-like constraints used by ensure_min_qty_like_live during backtests
symbols:
  BTCUSDT:
    precision:
      min_qty: 0.001
      step_size: 0.0001
    min_notional_usd: 5.0
    stops:
      initial_sl_atr_mult: 2.0    # optional symbol override
      trailing_atr_mult: 10.0      # optional symbol override
  SOLUSDT:
    precision:
      min_qty: 0.1
      step_size: 0.01
    min_notional_usd: 5.0
  ETHUSDT:
    precision:
      min_qty: 0.001
      step_size: 0.0001
    min_notional_usd: 5.0

backtest:
  # Default window: 2025-01-01 inclusive to 2025-08-01 exclusive ⇒ covers Jan–Jul 2025
  start_date_utc: "2025-01-01"
  end_date_utc:   "2025-08-01"

  progress_bar: true
  inputs:
    type: tick_csv
    path_pattern: "data/{symbol}/1m/{yyyymm}.csv"
    tick_path_pattern: "inputs/{symbol}/{symbol}-ticks-{yyyy}-{mm}.csv"
    tick_chunksize: 1000000  # rows per chunk for progress/low memory

  output:
    trades_csv: "outputs/{symbol}_trades_parity.csv"

  simulator:
    entry_fill: close        # "close" or "next_open"
    slippage_bps: 0
    atr_use_prior_bar_only: true   # new: strict timing for ATR during maintenance
