# configs/default.yaml
universe:
  symbols: [BTCUSDT]
windows:
  bar_minutes: 1
  atr_window: 14
  breakout_lookback: 25
  compression_lookback: 80
  compression_percentile: 70        # lower → more trades, higher → fewer trades

risk:
  atr_mult_sl: 25.0
  atr_mult_tp: 100.0
  fee_bps: 2.0                       # 2 bps per fill, applied on entry & exit
  breakeven_threshold_r: 0.6         # move to BE only if unrealized R ≥ this
  fee_buffer_r: 0.08                 # extra buffer (in R) for BE clamp (covers fees/slippage)

tsl:
  trail_activation_r: 0.5            # require this unrealized R before TSL turns on
  atr_mult_tsl: 30.0                  # chandelier width from highest close (long)
  trail_from: "highest_close"        # highest_close | highest_high

signal:
  breakout_offset_atr: 0.75          # breakout must exceed level by this ATR
  need_confirm_closes: 1             # confirm closes beyond breakout line
  min_body_ratio: 0.6                # body/true-range at confirmation
  allow_second_leg: true             # breakout → pullback → resumption
  cooldown_bars_after_regime_flip: 10

engine:
  order_on_next_open: true
  seed: 7

io:
  trades_csv: "{results_dir}/{symbol}_trades.csv"
  summary_csv: "{results_dir}/{symbol}_summary.csv"
