paths:
  inputs_dir: "inputs"
  outputs_dir: "outputs"

symbols: ["BTCUSDT", "ETHUSDT", "SOLUSDT"]

months: ["2025-01","2025-02","2025-03","2025-04","2025-05","2025-06","2025-07"]

warmup:
  min_1m_bars: 1000  # ensure indicators populated

regime:
  timeframes:
    "1m":  { lookback_closes: 30 }
    "5m":  { lookback_closes: 20 }
    "15m": { lookback_closes: 12 }
    "1h":  { lookback_closes: 8 }
  vote:
    require: 3

waves:
  enabled: true
  zigzag:
    atr_window: 30
    atr_mults: [0.7, 1.4, 3.0]
    max_lookback_bars: 2500
  thresholds:
    min_confidence: 0.55
    w2_posterior_min: 0.55
    w2_end_arm: 0.62
    block_if_correction_p: 0.60
    max_age_impulse_bars: 20

entry_gate:
  mode: "W2_to_W3_only"
  confirmations:
    micro_msb: true
    min_body_dom: 0.55
    donchian_breakout: { enabled: true, lookback: 20 }
  buffers:
    breakout_atr_mult: 0.20

entry:
  mode: "wavegate_momentum"
  momentum:
    zscore_window: 30
    zscore_k: 2.5
    min_body_dom: 0.55
    range_atr_min: 3.0
  breakout:
    buffer_atr_mult: 0.20

risk:
  atr:
    window: 30
  sl:
    mode: "atr"
    atr_mult: 15.0
  be:
    trigger_r_multiple: 0.5
  tsl:
    start_r_multiple: 4.0
    atr_mult: 7.0

position:
  qty_mode: "notional"  # "units" or "notional"
  notional_usd: 100      # used for P&L scaling; no brokerage here

logging:
  progress: true
  debug_blockers: true
  # throttle UI updates to keep bars smooth & fast
  progress_stride: 50     # update hook every N bars
  overall_bar: true       # show combined progress bar across symbols
