
# Minimal, non-duplicated config with strict adaptive defaults.
symbols: ["BTCUSDT"]   #, "ETHUSDT", "SOLUSDT"

paths:
  inputs_dir: "inputs"
  outputs_dir: "outputs"

# January–March example; extend as needed.
months: ["2025-01", "2025-02", "2025-03","2025-04", "2025-05", "2025-06", "2025-07"]

logging:
  progress: true
  progress_stride: 200

engine:
  warmup:
    min_1m_bars: 4000         # ~3 days (tunable)
    min_w2_candidates: 60     # ensure quantiles are meaningful

# ---------- Macro Regime (TSMOM) ----------
regime:
  ts_mom:
    require_majority: 3
    timeframes:
      - { tf: "1min", lookback_closes: 30 }   # 30 min
      - { tf: "5min",  lookback_closes: 20 }  # 100 min
      - { tf: "15min", lookback_closes: 12 }  # 180 min
      - { tf: "1h",    lookback_closes: 8 }   # 8 hours

# ---------- Event-Time Waves (CUSUM + WaveGate) ----------
waves:
  cusum:
    atr_window_1m: 200
    k_factor: 0.35
    k_min: 0.25
    k_max: 0.60

  adaptive:
    enabled: true
    vol_window_1m: 200
    atr_mult_range: [2.8, 7.5]
    atr_window_range: [180, 320]
    thresholds_quantile: 0.85
    max_age_bars_range: [70, 140]

  zigzag:
    max_lookback_bars: 1500

  fixed:
    atr_mult0: 2.8
    atr_window: 220
    w2_end_arm: 0.64
    w2_post_min: 0.60
    min_conf: 0.60
    max_age_bars: 110

# ---------- Entry Trigger (1m momentum bar) ----------
entry:
  momentum:
    zscore_window: 20
    min_body_dom: 0.60
  adaptive:
    enabled: true
    zscore_k_range: [1.7, 3.5]
    range_atr_min_range: [1.5, 4.5]
  fixed:
    zscore_k: 2.0
    range_atr_min: 1.5

# ---------- Risk Management ----------
risk:
  atr:
    window: 14
  sl:
    mode: "atr"   # structural W2 or ATR-based
    atr_mult: 15.0
  be:
    buffer:
      r_multiple: 0.02            # cover costs if very tight
      fees_bps_round_trip: 8.0
      slippage_bps: 6.0
  adaptive:
    enabled: true
    be_trigger_r_range: [0.4, 0.8]
    tsl_start_r_range: [1.0, 4.0]
    tsl_atr_mult_range: [5.0, 15.0]
  fixed:
    be_trigger_r: 0.50
    tsl_start_r: 1.0
    tsl_atr_mult: 10.0
